### ISSUE TITLE
Behaviour when trying to delete a Resource that is pointed to by other Resources

### ISSUE THREAD

**Issue by tobiasschweizer** [dasch-swiss/dsp-api#103]
What should the behaviour be when a user wants to delete a resource that is pointed to by other resources?

> Example: A user creates a resource A. Another user adds a text value to a resource B containing a standoff link to resource A. When the owner of resource A wants to delete his resource, should he be notified that there are links pointing to this resource (in the GUI)?

When resource A gets deleted, it is actually marked as deleted and it still exists in the triplestore, so the data is not corrupted. However, if a user looks at resource B and its text value, he sees that there is a standoff link, but because this standoff links points to resource A which is marked as deleted, the request that should get information about resource A (e.g., when the user hovers over the standoff link) fails (404).

**Comment by subotic** [comment]
If we allow deletion of resources, then the user should be able to do it. In your use case, the information shown when the user hovers over the standoff link could be the linked resource but marked as deleted. The user can then change the link, so it points to the last not deleted version. On the other hand, we could do this "automatically", which is probably a pain to implement. Just some thoughts.

**Comment by benjamingeer** [comment]
> The user can then change the link, so it points to the last not deleted version.

Resources aren't versioned.

**Comment by subotic** [comment]
>> The user can then change the link, so it points to the last not deleted version.

>Resources aren't versioned.

Ah, yes. I always forget this. Then it's even easier. We show a notification that the resource was deleted.

**Comment by benjamingeer** [comment]
What do we do about this:

The `Annotation` class has `owl:minCardinality 1` on property `isAnnotationOf`. User A makes an annotation on resource R, which is owned by user B. Then user B marks resource R as deleted. Now user A's annotation has a cardinality constraint violation.

I guess the only thing we can do is allow it.

**Comment by seakayone** [comment]
This issue has been inactive for a significant time, so we’re closing it for now. If it’s still relevant, feel free to reopen.
