### ISSUE TITLE
Bulk-import error report is too vague

### ISSUE THREAD

**Issue by mrivoal** [dasch-swiss/dsp-api#1050]
Hello there!

I am currently testing the bulk-import. In fact, the test addresses a 2500 lines XML file and I find the error messages quite vague. 

```
{"status":11,"error":"org.knora.webapi.BadRequestException: Invalid text: ''"}
```
or
```
{"status":11,"error":"org.knora.webapi.BadRequestException: Resource  is the target of a link, but was not provided in the request"}
```
At some point, it might be a good idea to provide a bit more details on these errors so that he/she can find them more easily.

**Comment by benjamingeer** [comment]
The second error looks like an error-handling bug. The first one needs improvement, too. Can you attach the XML file along with the ontologies and admin data so I can reproduce this?

**Comment by benjamingeer** [comment]
Thanks. I will need to be able to reproduce this to understand why the error messages are incorrect. Will try.
