### ISSUE TITLE
Implement a standoff editor

### ISSUE THREAD

**Issue by benjamingeer** [dasch-swiss/dsp-api#1111]
Wish list:

- A user-friendly text editing environment with built-in support for standoff markup
- The user can choose how each markup tag is represented visually, e.g.:
  - As highlighting or underlining in different colours
  - As text style (bold, italic, etc.)
  - As punctuation (e.g. large curly braces)
- Additional tag data is easy to display and edit
- The editor communicates with Knora API v2
- Drafts can be saved locally, without making new value versions in Knora

It's not clear whether this is feasible in a browser. It might be necessary to make a desktop app.

**Comment by loicjaouen** [comment]
i mentioned it earlier, but just in case: http://brat.nlplab.org/features.html

**Comment by benjamingeer** [comment]
I had a look at it when you first mentioned it, but it doesn't seem to be able to do annotations that are longer than one line.

**Comment by musicEnfanthen** [comment]
Just had an inspiring talk to @argimenes about his "The Codex" project last week, in which he implemented a highly configurable and customizable, stand-alone, purely JS-based standoff-properties-editor: https://github.com/argimenes/standoff-properties-editor

You can have a look at this demo: https://argimenes.github.io/standoff-properties-editor/

**Comment by mrivoal** [comment]
@musicEnfanthen It is funny that you mentioned this tool now. I just heard of it a few weeks ago and we have been having a look at the demo. It looks like a nice tool.

**Comment by benjamingeer** [comment]
@musicEnfanthen That editor looks very good. It doesn't work with Arabic text, though; I opened an issue about that: https://github.com/argimenes/standoff-properties-editor/issues/18.
