### ISSUE TITLE
Julian Day to Calendar Conversion in salsah datehelper.js

### ISSUE THREAD

**Issue by tobiasschweizer** [dasch-swiss/dsp-api#126]
Which is this correct now? The statement above (`parseInt`) was never used before. Can it be removed?

Could please check that the conversion functions in `datehelpers.js` are implemented correctly in `salsah/src/public/js/datehelpers.js`:
- `jd_to_gregorian`
- `jd_to_julian`

The thing is that Julian Dates with a fraction of 0.5 refer to midnight.

``` javascript

S.jd_to_gregorian = function(jd) {

var wjd; 

wjd = Math.floor(jd - 0.5) + 0.5;
```

So if `jd` has at least a fraction of 0.5, the result is  2299160.5, otherwise it is 2299159.5 which is the day before.

**Comment by seakayone** [comment]
This issue has been inactive for a significant time, so we’re closing it for now. If it’s still relevant, feel free to reopen.
