### ISSUE TITLE
Error in projects route

### ISSUE THREAD

**Issue by tobiasschweizer** [dasch-swiss/dsp-api#1431]
When opening the extended search form on <https://app1.dasch.swiss/>, an error occurs:

https://api.dasch.swiss/v1/projects
> {"status":4,"error":"org.knora.webapi.InconsistentTriplestoreDataException: No value found for SPARQL query variable 'o' in query result row"}

**Comment by tobiasschweizer** [comment]
Probably this should be https://api.dasch.swiss/admin/projects (admin api, not v1)

https://docs.knora.org/paradox/03-apis/api-admin/projects.html

**Comment by tobiasschweizer** [comment]
`v1/projects` should work since there is a test for it org/knora/webapi/e2e/v1/ProjectsV1E2ESpec.scala

**Comment by tobiasschweizer** [comment]
`v1/projects` works for me locally

**Comment by subotic** [comment]
There should still be a `v1/projects` route because it is used by the old Salsah GUI. I never removed it. That's why there are still tests. The v1 „admin“ routes are read only.

**Comment by tobiasschweizer** [comment]
ok, but there is a problem with https://api.dasch.swiss/v1/projects. Maybe a config issue? Incomplete project data?

**Comment by subotic** [comment]
Hmm, good that we have tests that should catch these sort for things ...

Probably incompatibility with the data stored inside the triplestore. The V1 "admin" routes (users, projects, lists) still use the "old" implementation based on select queries. Maybe it would make sense, to actually call the new admin responders and then convert the result to what V1 is expecting. Then we could get rid of the old V1 code for users and projects.

Anyway, this will have to wait after my vacation, if there are no volunteers.

**Comment by tobiasschweizer** [comment]
>  Maybe it would make sense, to actually call the new admin responders and then convert the result to what V1 is expecting. Then we could get rid of the old V1 code for users and projects.

Yes, that would be good!

> Anyway, this will have to wait after my vacation, if there are no volunteers.

I think that's ok. Enjoy your stay!
