### ISSUE TITLE
Searching with "_" gives no results

### ISSUE THREAD

**Issue by mrivoal** [dasch-swiss/dsp-api#1434]
On Salsah 1.5 and your KUIRL test server, using the fulltext search with "_" gives no results. 

I initially thought that it happened only when the `rdfs:label` includes this character, but it also happens for a standard `TextValue` property.

Given this resource: 
![Capture d’écran 2019-09-10 à 14 35 17](https://user-images.githubusercontent.com/17294309/64614433-cd2a2a00-d3d8-11e9-9fe9-ad82529f2851.png)

The following search in unsuccessful:

![Capture d’écran 2019-09-10 à 14 40 13](https://user-images.githubusercontent.com/17294309/64614501-efbc4300-d3d8-11e9-82cf-8162dadb5e9b.png)

This one is even worse:

![Capture d’écran 2019-09-10 à 14 41 08](https://user-images.githubusercontent.com/17294309/64614589-19756a00-d3d9-11e9-83b8-6e4ee172264c.png)

**Comment by loicjaouen** [comment]
for reference: [DSP-357](https://dasch.myjetbrains.com/youtrack/issue/DSP-357)
