### ISSUE TITLE
Create a better Way of Creating a Triplestore-Repository

### ISSUE THREAD

**Issue by tobiasschweizer** [dasch-swiss/dsp-api#144]
We should write a scala objects with methods or a commandline program that configures:
-  type of triplestore
- consistency checking on or off
- a list of ontology files with named graphs and their order
- list of data files with named graphs

Then this could be used also in tests so we could change its configuration. This would replace our cli scripts that we have at the moment.

**Comment by seakayone** [comment]
This issue has been inactive for a significant time, so we’re closing it for now. If it’s still relevant, feel free to reopen.
