### ISSUE TITLE
Load a project specific design

### ISSUE THREAD

**Issue by tobiasschweizer** [dasch-swiss/dsp-api#147]
In the old SALSAH, the design is reloaded when switching a project.

This is handled in `index.html` in the method `SALSAH.reset_project_selection`.

When a project is chosen from the project selection, a POST request to the route `userdata` is made submitting the chosen project's id. The answer consists just of the Api status and the userdata. In the callback, the function `SALSAH.reload_css()` is called, reloading the CSS.

However, I do not understand what the Post request to userdata actually does. Do we have to implement the route `userdata` at all?

**Comment by seakayone** [comment]
This issue has been inactive for a significant time, so we’re closing it for now. If it’s still relevant, feel free to reopen.
