### ISSUE TITLE
How should a project's design be reloaded in Knora/SALSAH?

### ISSUE THREAD

**Issue by tobiasschweizer** [dasch-swiss/dsp-api#148]
How should we implement `SALSAH.reload_css` in Knora/SALSAH?

It is needed to load project specific designs.

``` javascript
SALSAH.reload_css = function() {
    var href = $('#loadcss').attr('href'); + ',#';
    if ((SALSAH.userdata !== null) && (SALSAH.userdata.active_project !== undefined)) href += '&project_id=' + SALSAH.userdata.active_project;

    $('#loadcss').attr({href: href});
}
```

In the head of the HTML served on the first request, the CSS is loaded tthrough a link tag:

```
<link id="loadcss" rel="stylesheet" href="http://iml-castafiore.iml.unibas.ch/salsah/app/themes/loadcss.php?name=workwin,win,search,dock,tabs,imagebase,propedit,avplayer&project_id=8" />
```

The function `SALSAH.reload_css` modifies its `href`, so different CSS is loaded.

 CC @milchkannen

**Comment by seakayone** [comment]
This issue has been inactive for a significant time, so we’re closing it for now. If it’s still relevant, feel free to reopen.
