### ISSUE TITLE
SALSAH-Login: login is sent twice after hitting return 

### ISSUE THREAD

**Issue by tobiasschweizer** [dasch-swiss/dsp-api#151]
When the login form is sent by hitting return in the password input field, the POST request is done twice. 

in `index.html`:

```
<tr><td id="password_label"></td><td>:</td><td><input type="password" name="password" id="password" onKeyDown="if (event.keyCode == 13) $('#login_button').click();" /></td></tr>
```

**Comment by subotic** [comment]
Yes, see http://git.iml.unibas.ch/salsah-suite/knora/issues/196

At that time, it was even stranger:
- Clicking the login button sends out **one** login request (correct behavior)
- Pressing the enter button sends out **two** login requests (wrong behavior)

Is it still like this?

**Comment by tobiasschweizer** [comment]
Yes, this is excactly the problem
