### ISSUE TITLE
Resource Locked when running automated Browser tests 

### ISSUE THREAD

**Issue by tobiasschweizer** [dasch-swiss/dsp-api#153]
When I run the automated browser tests with Fuseki, sometimes I get the following error message when trying to add new values of a property:

```
Could not acquire update lock on resource http://data.knora.org/691e7e2244d5 for API request 4498d921-7519-4940-a6d2-9664a6167b7e within 1000 ms, because API request 6d32a605-a832-4c3e-b901-58f6afd9bf5d is holding it
webapi org.knora.webapi.ApplicationLockException: Could not acquire update lock on resource http://data.knora.org/691e7e2244d5 for API request 4498d921-7519-4940-a6d2-9664a6167b7e within 1000 ms, because API request 6d32a605-a832-4c3e-b901-58f6afd9bf5d is holding it
webapi  at org.knora.webapi.responders.ResourceLocker$.org$knora$webapi$responders$ResourceLocker$$acquireOrIncrementLock(ResourceLocker.scala:133)
```

As I run several edit operations after one another automatically, could this problem just be caused by the fact that a new edit request is being sent to the server when the old is still being processed? I experienced Fuseki to be slower when doing updates than GraphDB.

**Comment by tobiasschweizer** [comment]
In a case a browser would terminate the connection right after having sent a Post or Put request, how long would the resource be locked until it is freed?

I am asking because I reload the page after each test.

**Comment by benjamingeer** [comment]
As it says in the error message, it gives up after 1000 ms. This is hard-coded, you can change it in `ResourceLocker`. Maybe 5 seconds would be better.
