### ISSUE TITLE
knora-api:resourceProperty should not be a resource property

### ISSUE THREAD

**Issue by benjamingeer** [dasch-swiss/dsp-api#1631]
The client code would like to be able to assume that if a property has `knora-api:isResourceProperty true`, it also has a `knora-api:objectType`. The only exception seems to be `knora-api:resourceProperty` itself. So `knora-api:resourceProperty` should not have `knora-api:isResourceProperty true`.

**Comment by tobiasschweizer** [comment]
This will require an adaption of the specs in knora-api-lib-js.
