### ISSUE TITLE
Add a route for adding another StillImageFileValue to an existing Representation

### ISSUE THREAD

**Issue by benjamingeer** [dasch-swiss/dsp-api#164]
@sofiag needs to create representations containing multiple files. Probably the easiest and most sensible way to do this is to create a representation containing one file, then do additional POST requests to add the additional files. So we need a route for that.

**Comment by tobiasschweizer** [comment]
Yesterday, we discussed the option of creating a page with several image representations. Moreover, the page should be an abstract entity like a book that may have representations pointing to it (see https://github.com/dhlab-basel/Knora/issues/355). 

However, the implications for the routes are quite heavy. The suggested way of adding more representations later is feasible (unlike one heavy multipart request) but I also need to figure out a way to make this compatible with the handling XML files.

**Comment by tobiasschweizer** [comment]
Also relevant for v2!

But actually we cannot do anything like that without changing v1 at the same time.
