### ISSUE TITLE
Store geometry as RDF rather than JSON

### ISSUE THREAD

**Issue by benjamingeer** [dasch-swiss/dsp-api#169]
Currently a `knora-base:GeomValue` contains an opaque JSON string. It would be better to store a geometric shape in RDF instead. Then you could search for rectangles, circles, etc. Also, the current JSON representation isn't documented. An RDF representation would have built-in documentation in `knora-base`.

**Comment by mrivoal** [comment]
I think I would agree on this (if I may).

People will need to access `knora-base:GeomValue` and export them for further post-treatments. It would be much easily accessible to the common user it he could access this data within the GUI and not only in the API.

**Comment by tobiasschweizer** [comment]
Hey guy, what should we do here for v2?

Actually, Lukas thought about using third party front-ends like Mirador that supports SVG shapes.

I tried the demo and it did not work very well: http://projectmirador.org/demo/

**Comment by mrivoal** [comment]
Maybe it depends on what we plan to do with image annotation and `knora-base:Region` ?
Are we speaking about a 2D annotation tool? Or also 3D? 

It may exceed the scope of the discussion, but I think that, in v2, we should be able to custom `knora-base:Region` with all kinds of properties (including properties pointing to `ListValue`, `GeonameValue`). This would considerably increase Knora's potential on semantic annotation.

Maybe we should talk about it altogether?

By the way, an interesting work on **2D/3D semantic annotation of spatialized image** is a french project called Aïoli that will be released soon. Here is a PhD thesis on this kind of annotations:  [https://pastel.archives-ouvertes.fr/tel-01304776/document](url) and here a presentation  on the same tool: [http://fms2.cerimes.fr/vod/media/canalu/documents/humanum/aioli.reality.based.3d.annotation.cloud.service_34027/04.manuel.a.pres.3dws.parthenos.pdf](url)

Ps: I also tried the Mirador demo and I did not find it that bad... (even if some features are lacking, in my opinion).

**Comment by aeneaskaiser** [comment]
If/when we decide to store the `knora-base:GeomValue` as RDF rather than JSON, we can at the same time simplify the `radius` property of circle shaped region geometries. 

Currently `radius` has sub-properties `x` and `y` storing the radius relative to the width respectively height of the linked image. This is redundant information, since one value can always be calculated from the other if the ratio of width and height is known.
With a documented convention like 'always store the radius relative to the width', we could store just one value for the radius.

**Comment by tobiasschweizer** [comment]
I discovered another problem: the color is stored in the geometry JSON-string and as a color property. This is redundant and may get inconsistent.
