### ISSUE TITLE
docs: Bazel build tool is missing in Knora Getting Started for Developers

### ISSUE THREAD

**Issue by musicEnfanthen** [dasch-swiss/dsp-api#1731]
In the DSP documentation about "[How to install Knora](https://docs.dasch.swiss/developers/knora/getting-started/)", a section about the Bazel build tool is missing. Without Bazel the stack-up command will not run:

```
make stack-up

-------
make: bazel: No such file or directory
make: *** [docker-build-knora-api-image] Error 1
-------
```

Bazel is only mentioned in the knora-api [README](https://github.com/dasch-swiss/knora-api) as a prerequisite.

**Comment by BalduinLandolt** [comment]
has been solved since
