### ISSUE TITLE
Return multiple file values in /resources API route

### ISSUE THREAD

**Issue by benjamingeer** [dasch-swiss/dsp-api#174]
On the `wip/sofiag` branch, @sofiag creates a resource using the script `create_webPTM_resource.py`. The resource has multiple file values, and these need to be returned by the `/resources` route. I don't know why the file values aren't returned under `locations` in the API response. In any case, `locations` is probably too limited, and it would be better to have an option (e.g. an extra query parameter in the route) that would return the file values along with the other values of the resource.

**Comment by benjamingeer** [comment]
There are at least two problems here:

* The test script actually uploads only one file, and a preview is created for it; that makes two files. But the preview was not recognised as such because of a bug that had been fixed on the `wip/test_ontology` branch.
* No files appeared under `locations` in an API response for an unknown user, because the files were created with no permissions, because of #79. There's a temporary workaround on the `wip/test_ontology` branch, which puts default permissions on `knora-base:hasStillImageFileValue`.

I merged `wip/test_ontology` into `wip/sofiag`, so now the API response includes `locations`, `preview`, and `locdata`. @sofiag, can you try it now and see if this is adequate for now? To add multiple files, I think you'll have to create the resource first with one file, then add each additional file separately.

cc @tobiasschweizer

**Comment by seakayone** [comment]
This issue has been inactive for a significant time, so we’re closing it for now. If it’s still relevant, feel free to reopen.
