### ISSUE TITLE
Consider allowing projects to specify custom IRIs for new resources

### ISSUE THREAD

**Issue by benjamingeer** [dasch-swiss/dsp-api#176]
If a project already has unique IDs for the resources it wants to create in Knora, it could be convenient to allow them to specify their own unique IRI for each resource, using a project-specific IRI prefix, rather than have an IRI generated randomly. The alternative is to store the existing unique ID as the value of a property of the resource.

What do you think, @lrosenth?

**Comment by sofiag** [comment]
That could be very convenient also for integrating RTI eventually.

**Comment by loicjaouen** [comment]
@sofiag : what's RTI ?

It is essential to be able to import data that is already available without breaking compatibility of the objects referencing to it.

**Comment by sofiag** [comment]
@loicjaouen , It stands for Reflectance transformation imaging, It is the digital materiality project.

**Comment by mrivoal** [comment]
Yes, Ben, I think your suggestion is perfectly right. In the "Dessin de dieu" project, the team already uses internally its own unique IDs (and they are of some significance to them). Keeping these IDs in the IRI of the resources would be a good thing. But stocking them in the value of a property would also do if the alternative is too cumbersome.

**Comment by mattssp** [comment]
I would strongly vote for that. This is absolutely essential.

**Comment by mattssp** [comment]
Is this still alive? In my project, I import a lot of data into knora from a different database, overwriting everything on every load (until salsah is in place and everything is migrated...) After every import, all id's have changed, which is inconvenient for the users, eg. if they bookmark stuff. Also, it would be nice to be able to anticipate id's of objects that are not yet in knora.
As stated above, an alternative to allow for custom IRIs would be to have a custom id field on the relevant resource types. Is this the way to go? Is there a way to enforce a unique constraint on a field in knora? Would it even make sense to have a construct for alternative ids on resources (to cover legacy naming systems) in knora-base?

**Comment by benjamingeer** [comment]
I think we will have to do something like this, but I'm not sure which is the better approach: custom IRIs or a unique ID property.

Either way is possible, especially now that Knora IRIs contain the project ID, which is like a namespace for the rest of the IRI.

I suppose there will be lots of different sorts of unique IDs that people will want to include for different reasons. Some of these could just be legacy database IDs, but others could be standard IDs such as [GND](http://www.dnb.de/EN/Standardisierung/GND/gnd_node.html) IDs. A single resource could even have several different IDs that are meaningful to different systems. This suggests that it would be more useful to store them as property values than as part of a resource IRI. That would also make it possible to search for them. And you could mark a resource with ID NNN as deleted, and then create another resource with the same ID NNN.

Perhaps we could make a `UniqueIDValue` class (a subclass of `Value`) for things like this, which would just store an `xsd:string`. Then you could define a property such as `hasGND` with `objectClassConstraint UniqueIDValue`.

> Is there a way to enforce a unique constraint on a field in knora?

With GraphDB, I think we could do this with a consistency rule, e.g. if a predicate (such as `hasGND`) points to a `UniqueIDValue` containing a certain ID, there must be no other triple with the same predicate pointing to a `UniqueIDValue` containing the same ID.

Otherwise, it's difficult for the Knora API server to enforce uniqueness. The difficulty is in avoiding this [race condition](http://www.knora.org/documentation/manual/rst/knora-api-server/design-documentation/triplestore-updates.html#application-level-locking) described in the Knora design docs:

> The ‘read committed’ isolation level cannot prevent a scenario where two users want to add the same data at the same time. It is possible that both requests would do pre-update checks and simultaneously find that it is OK to add the data, and that both updates would then succeed, inserting redundant data and possibly violating ontology constraints.

When updating a single resource, we prevent this problem by using an application-level lock on the resource. But to guarantee that an IRI (or a value) is unique in the repository, you would have to lock the whole repository during the update, which would be inefficient. That's why we currently use [version 4 UUIDs](https://en.wikipedia.org/wiki/Universally_unique_identifier#Version_4_.28random.29) as unique IDs in IRIs: "for there to be a one in a billion chance of duplication, 103 trillion version 4 UUIDs must be generated" (in a single project).

In the near future, we'd like projects to be able to use the new XML bulk data import functionality rather than generating RDF and loading it into the triplestore directly:

http://www.knora.org/documentation/manual/rst/knora-api-server/api_v1/adding-resources.html#adding-multiple-resources-in-a-single-request

The XML import functionality is still incomplete (#434 #454 #455 #456), however.

**Comment by mattssp** [comment]
Thanks, Ben. So I think, for me, the way to go would be to have my legacy ids in a string field for now and check for uniqueness on application level (which is not hard as in a one time load). Later I can migrate to UniqueIDValue if it gets implemented. I will try to avoid adding more than 103 trillion records until then.

**Comment by seakayone** [comment]
This issue has been inactive for a significant time, so we’re closing it for now. If it’s still relevant, feel free to reopen.
