### ISSUE TITLE
Consider supporting resources that are reifications

### ISSUE THREAD

**Issue by benjamingeer** [dasch-swiss/dsp-api#178]
Use case: in a historical research project, there's a resource class `Person`, and a resource class `Place`. We want to indicate the places where each `Person` lived. We also need to indicate the dates when the `Person` lived in each `Place`, and the source of that information. We can't put this information in `Place`, because we don't want to represent places redundantly for different persons. Therefore, we need another class, `PersonPlace`, containing the dates and sources. Now a `Person` has a link to a `PersonPlace`, which has a link to a `Place`. But for searches, it would be more convenient to have a direct link between the `Person` and the `Place`. @lrosenth had this idea: Would it be possible to make `PersonPlace` a reification of such a direct link?

(The example is from the project "Databank of historical names, places and lemmas" of the [Swiss Law Sources Foundation](https://www.ssrq-sds-fds.ch).)

**Comment by loicjaouen** [comment]
that sounds very similar to the test case described there:
https://www.maillist.unibas.ch/pipermail/knora-user/2016-June/000072.html

**Comment by seakayone** [comment]
This issue has been inactive for a significant time, so we’re closing it for now. If it’s still relevant, feel free to reopen.
