### ISSUE TITLE
Missing CORS headers

### ISSUE THREAD

**Issue by loicjaouen** [dasch-swiss/dsp-api#179]
branch develop, commit 98a88548f6da4b4f79519adb7a5d31348ea1a966

At login, the POST request to http://localhost:3333/v1/session is fine.
Later on creating a resource (POST http://localhost:3333/v1/resources) fails with a missing CORS header.

I don't see why the CORS trait would not be applied to the `resource` route.

**Comment by loicjaouen** [comment]
it happened again and it shows that this is my misunderstanding of Chrome error message:

```
XMLHttpRequest cannot load http://localhost:3333/v1/resources.
No 'Access-Control-Allow-Origin' header is present on the requested resource.
Origin 'http://localhost:3335' is therefore not allowed access.
The response had HTTP status code 400.
```

The request reaches the server fine (after an OPTION preflight request granting the right permissions).
The server answers with a 400 status code and no 'Access-Control-Allow-Origin' header.
Then Chrome says: `Origin 'http://localhost:3335' is therefore not allowed access.` even though the request was sent.

**Comment by benjamingeer** [comment]
I learned last week that sometimes this happens when the API server could not parse the JSON in the POST request; see pull request #261. I will try to fix this next week.

**Comment by loicjaouen** [comment]
exactly, I had the issue when passing the wrong type for a value (the parser complains of not being able to parse, exception is raised and ends up in a 400 status code)

**Comment by subotic** [comment]
Maybe this will resolve itself with #273 . I'm exchanging our own CORS implementation for a new library, which should behave better.

**Comment by benjamingeer** [comment]
I'll wait until #273 is merged and look at this again then.

**Comment by subotic** [comment]
Is this still an issue?

**Comment by benjamingeer** [comment]
We need to test sending invalid JSON in a POST request to see if this is still an issue.
