### ISSUE TITLE
List Nodes if Type Date Value

### ISSUE THREAD

**Issue by tobiasschweizer** [dasch-swiss/dsp-api#193]
We should support date labels, e.g. the first Petersburg time of Leonhard Euler.

These labels could be represented like a flat list, but the list nodes would have to be represented as date values so someone could search for dates and find these resources.

We should also support:
- terminus ante/post quem: must be before or after the period of a specified date
- imprecision: add a date range when a date is unknown (represent the unknown as a date range). This range depends on the project. In case of the unknown date of death of a person, we could assume at max. 100 years after his birth. In an other case, another range would be more appropriate.

**Comment by seakayone** [comment]
This issue has been inactive for a significant time, so we’re closing it for now. If it’s still relevant, feel free to reopen.
