### ISSUE TITLE
Implement monitoring

### ISSUE THREAD

**Issue by benjamingeer** [dasch-swiss/dsp-api#2]
Steps:

- [x] measuring response times (done in PR https://github.com/dhlab-basel/Knora/pull/1347)
- [ ] expose metric to Prometheus
- [ ] provide simple GUI to visualize the metrics

**Comment by subotic** [comment]
http://kamon.io/documentation/1.x/recipes/monitoring-akka-quickstart/

**Comment by subotic** [comment]
Taking another stab at this. This time in smaller steps.

First adding the ability to measure response times:
https://blog.softwaremill.com/measuring-response-time-in-akka-http-7b6312ec70cf

**Comment by subotic** [comment]
The second step is to expose this and other metrics over a port so that [Prometheus](https://prometheus.io) can scrape it.

**Comment by subotic** [comment]
The third step is to provide a simple GUI for visualization of the collected metrics from Prometheus
