### ISSUE TITLE
(start view : last activity) Allow users to subscribe to external projects

### ISSUE THREAD

**Issue by jroland01** [dasch-swiss/dsp-api#204]
Some users have expressed a need to keep up with updates related to projects in their field, without being "official" members of those projects. Could we consider having a way to "subscribe" to external project updates (e.g. similar to RSS), which integrates into the user's activity feed ? [See wireframe](https://projects.invisionapp.com/d/main#/console/7940249/170749729/preview)

**Comment by milchkannen** [comment]
We can implement something like "Watch" with the same principle as GitHub has.

**Comment by seakayone** [comment]
This issue has been inactive for a significant time, so we’re closing it for now. If it’s still relevant, feel free to reopen.
