### ISSUE TITLE
(search panel : extended search) Allow users to build advanced queries in the search field, using predefined operators

### ISSUE THREAD

**Issue by jroland01** [dasch-swiss/dsp-api#211]
Salsah could allow for building advanced queries (e.g. similar to Google Search Operators) for advanced users, unsatisfied with regular / extended search. These queries could be entered directly into the "Search" field, using predefined operators.

**Comment by seakayone** [comment]
This issue has been inactive for a significant time, so we’re closing it for now. If it’s still relevant, feel free to reopen.
