### ISSUE TITLE
(search panel : extended search) Facilitate reuse of advanced queries through sharing, importing, etc.

### ISSUE THREAD

**Issue by jroland01** [dasch-swiss/dsp-api#213]
Searching as in #ES2 will require at least some knowledge of Salsah Search Operators, and skills at building queries. This can be mitigated through sharing / importing the most commonly used queries ("library of queries") among users, and providing templates for advanced queries where "basic" users will replace parameters / fields with their own values. The "Saved search queries" tab could probably be used to this effect.

**Comment by seakayone** [comment]
This issue has been inactive for a significant time, so we’re closing it for now. If it’s still relevant, feel free to reopen.
