### ISSUE TITLE
(search results : light table) Add faceted navigation to help users better sort search results

### ISSUE THREAD

**Issue by jroland01** [dasch-swiss/dsp-api#216]
![salsah_preview_mode_-_invision](https://cloud.githubusercontent.com/assets/1269913/17768471/6212a2c6-6534-11e6-8c68-c48c1ee16e1d.jpg)

Have you thought of introducing a faceted navigation, e.g. on the left, similar to LinkedIn search results, to further refine the search results according to different dimensions (facets), e.g. resource type, date, author, etc. ? I believe this would be a good way, to assist in exploring the database, and to help in refining / building queries for the non -advanced users.

**Comment by loicjaouen** [comment]
faceted navigation: fully agree, here's an article about DBPedia faceted navigation (using semantic nature of the data)
http://wiki.dbpedia.org/projects/faceted-wikipedia-search

**Comment by milchkannen** [comment]
1: the left side is reserved for project setting stuff.
2: would be the better place.

**Comment by jroland01** [comment]
@milchkannen Two points here : 

+ Maybe I misunderstand something, but why does project setting stuff menus have to be displayed simultaneously with search results ? Wouldn't you have a top-level "Settings" menu somewhere, and then settings -specific pages ? Why would a user want to have all project settings available next to her search results ?

+ Given Salsah's specificity (it's generic, can handle complex data models, etc.), I would strongly recommend to implement a vertical faceted search (see LinkedIn Search's), which allows for much more flexibility (more facets, possibility to dynamically add facets, variation in the number of facets depending on the projects, etc.) and is usually easier to navigate.

**Comment by milchkannen** [comment]
We can have a faceted search navigation on the top of the main view, as you suggested in number 2. 
By the way: the project menu is not always displayed. But the user can open it every time — like in gitlab. It should be something like the main / core menu. I'm thinking to remove the second row from the toolbar (Project activity, Last activity, My collections) on the top. The menu there could be a new menu item (Dashboard) in the left menu. I will redesign it soon and I will think about a vertical faceted search.
Perhaps one menu (or faceted search) on the left, one on the right hand side?

**Comment by jroland01** [comment]
@milchkannen I think we really need to "zone" the Salsah application screen to make sure we have a consistent navigation logic across screens. This is really important so that users will discover this logic, understand it and learn it. Below is an example using an horizontal main menu (to keep close to what you suggested initially), with a vertical secondary menu on the left (to allow for a flexible faceted search) where I tried to fit what you have on your wireframes (I did that really quickly for illustration purposes only, so it's rough and most probably misses things) : 

![salsah zoning](https://cloud.githubusercontent.com/assets/1269913/18120100/3dd2c59c-6f5e-11e6-9eab-e0c1940ccc04.png)

@milchkannen Another question : Users have expressed the need to see several resources simultaneously (quote from Anton Webern interview : "the ability to view several objects simultaneously (e.g. for the transcription process : several sources as images + transcription) should be maintained in Salsah"). How will this be handled in Salsah v2 since you seem to be departing from a "windows -like" web based GUI (like the one in Salsah v1) ? Will individual resources open in the main part of the screen (same window), a new browser window, a new browser tab, a floating window (somehow), etc. ?

**Comment by loicjaouen** [comment]
@jroland01 : zoning : cool, might be helpful for the user but it is definitely helpful right now for me :)

I would then like to see consistency in the behaviour:
- if menu items change the window below
- then make the actions that change the window below a menu item
- or put the effect of non menu action elsewhere (modal window for exemple)

**Comment by milchkannen** [comment]
I decided yesterday to remove the horizontal main menu. It takes too much space and I don't like it anymore.
But now I have to think about it. I'm trying to design new mockups today — based on the issues here, my local notes and the Angular2 component concept. I hope that I can send you a proper solution tomorrow (or at least on Friday) to work on it on Monday. 

For the resource comparison view I suggested to create a split screen view with a maximum of six boxes. We already talked about it with the example of CodePen and other online code editors.

**Comment by jroland01** [comment]
@milchkannen I would say it's important to think about the requirements when devising a navigation structure. Some examples : 

+ Gmail uses a vertical main navigation because you can potentially add as many boxes or labels as you want (unlimited), while it uses a horizontal secondary action bar on top of individual emails because there is only a limited number of things you can do with an email (or sort of)

+ GitLab uses a vertical main navigation and a horizontal secondary navigation (filters), probably because they have more TOP level items = 9 - 10 (e.g. "Projects", "To Dos", "Activity", etc.) than they have secondary filters = 4 at maximum.

Etc.

I believe that in the case of Salsah we need to take the following into account : 

+ There are probably a very limited number of TOP level menu items (e.g. "Activity", "Collections", "Resources", what else ?) - it would be good to have a definitive list
+ I am not sure whether you intend to display all resource types in a secondary menu / filter (see my 4th screen), but this can probably extend depending on the number of resources
+ The faceted search should be implemented vertically (see previous comments in this thread), preferably on the left (more standard) - this would be difficult to match with a vertical main navigation

Thus, this (probably more second level filters than TOP level menus on average, faceted navigation) would speak in favor of a horizontal main navigation (needs to be validated with the full list of items).

Regarding resource comparison : Sorry I missed that discussion. Would that also include some kind of full-screen distraction-free mode (remove menus, other stuff) for sustained work on resources ?

**Comment by seakayone** [comment]
This issue has been inactive for a significant time, so we’re closing it for now. If it’s still relevant, feel free to reopen.
