### ISSUE TITLE
(table editor view) choose columns

### ISSUE THREAD

**Issue by loicjaouen** [dasch-swiss/dsp-api#224]
it would be handy to be able to select the columns that show up, and that the columns could span over multiple objects.

As a use case: I want to clean-up pictures date according to different pictures and life-span of the photographer, from the link (Picture -> Author) I want to select Picture.title, Picture.date, Author.birthdate, Author.deathdate, sort by date and fix the outliers.

**Comment by milchkannen** [comment]
That's a nice idea.But how can we display that table? A picture would be nice...

**Comment by milchkannen** [comment]
We need something like an error handling ;D
The user sets the capture date of a picture on 1920. But the photographer was born in 1930. 
The system should recognise the "error" and has to show an alert/dialog box?!
