### ISSUE TITLE
Ease data input for composite resource classes

### ISSUE THREAD

**Issue by mrivoal** [dasch-swiss/dsp-api#231]
During data input, resource class embedding other resource classes (in the UML composite meaning) should be editable in a single form with expandable sub-form as in WISSKI example below:

![capture d ecran 2016-08-18 a 10 30 22](https://cloud.githubusercontent.com/assets/17294309/17813378/6441392a-662b-11e6-84cf-cadf1198612b.png)

According to the user’s wish :
- a **click on the red +** would allow the user to display the Geburstdaten objet in a separate window,
- while **a click on a minus sign** would shrink the whole Geburstdaten object.

Here, `Geburstdaten` is a distinct resource class, with properties of its own (`geburtsdatum` ; `geburtsort`).
The `Geburstdaten` class should be somehow linked as a `knora-base :CompositeClassOf` the resource class `Person` (which means the GUI requirements would impact the knora-base ontology… this obviously has to be discussed), because it makes sense to distinguish between :
- resource classes created because the RDF modelling requires it (`Geburtsdaten` should not exists on its own because it is a composite part of `Person` and yet it has to be a resource class of its own in the modelling process)
- and resource classes that are semantically different and independent objets (such as a `Painting` would be for Albrecht Dürer as a `Person`).
  The **light table screen** should display semantically different and independent resource classes as objects, whereas the composite resource classes would not appear on their own : `Geburstdaten` would not appear as a search result, but the `Person` would. 

I think it still makes completely sense if linked objects appear in separated (and linked) windows in the « **exploring/browsing** » mode, when users are browsing through data.
Thus, there could be a « **data entry mode** », and an «**explore/browse mode** » with distinct features (and distinct left side panel features) according to the different needs of the users during these activities.

**Comment by loicjaouen** [comment]
With a composition indication in the data-model (cf #233) the GUI knows when to expand "inline" (within the same window).

Let's have a Person with name, activity and a list of events:
![data-model](https://cloud.githubusercontent.com/assets/3933654/17849227/1f7c4d8c-6858-11e6-902b-360bb087e742.png)
(as stated before about composition, _Event_ is a _Resource_ class of it own, but not existing outside of _Person_)

A _Person_ with no event would look like:
![birthdate-empty_events](https://cloud.githubusercontent.com/assets/3933654/17849289/72ff3f00-6858-11e6-852b-ab33cba81dbe.png)

The "plus" icon would expand the section to add events:
![birthdate](https://cloud.githubusercontent.com/assets/3933654/17850959/f191ba8a-685f-11e6-8f9c-5100e702ad58.png)

With still the opportunity to edit the _Event_ in its own window, with the green north-east arrow button.

This is specially needed if the class is complex.

I guess a class will have different views, Viewers/Editors with different granularity of details to be displayed/editable.

**Comment by jroland01** [comment]
This (below) is just for discussion's sake (very rough, probably missing stuff). 

Would this work, with inline editing ?

+ it's more "web -like" (in accordance with Salsah's other wireframes so far)
+ it's simpler, less cluttered (less "system -like" with less fields, actions exposed)
+ it's more human readable ("Birth on ... in ... " is easier to read than "Birth -> Date -> Place")

![person edit](https://cloud.githubusercontent.com/assets/1269913/17884835/a43391f8-691a-11e6-87b8-a902856275cc.png)

What is the requirement for editing events in their own window ?

**Comment by seakayone** [comment]
This issue has been inactive for a significant time, so we’re closing it for now. If it’s still relevant, feel free to reopen.
