### ISSUE TITLE
Missing screens

### ISSUE THREAD

**Issue by mrivoal** [dasch-swiss/dsp-api#232]
I think some points are somehow missing in the wireframes : 
- **extended search** (an insight on what it may or should look like would be great)
- extended search for **table edit** (possibly the same as the above extended search… but not quite sure, if this search must allow the user to choose the most relevant columns/properties for different resources classes, as suggested by Loïc on users demand)
- search results : what will be the representation of an object (e.g. Author) with links to and/or links from other objects (resource pointer) (e.g. Books linked to an Author) and how will the user sort and explore these often heterogeneous links ?
- graph visualization/exploration tool (even if I know it is a bit early to discuss this, I just want to stress it out, so that we don’t forget it).

**Comment by milchkannen** [comment]
- extended search: it's something like we have already. See the first page on the salsah.org/tableedit but with a better styling (I will look for the right salsah branch where I already created a better extended search model). The fields depending always on the project settings.
- we would have only one extended search in the future with different views of the search results (incl. the table editor view)

**Comment by mrivoal** [comment]
Yes, but the "extended search" functionalities we currently have don't cover users' standard needs in a database. See #227.

**Comment by milchkannen** [comment]
okay I see...you're right. Yes, we have to discuss the extended-search functionalities

**Comment by seakayone** [comment]
This issue has been inactive for a significant time, so we’re closing it for now. If it’s still relevant, feel free to reopen.
