### ISSUE TITLE
Consistency rules for missing cardinalities are too lenient

### ISSUE THREAD

**Issue by benjamingeer** [dasch-swiss/dsp-api#235]
The consistency rules `resource_prop_cardinality_any` and `value_prop_cardinality_any` will overlook a missing cardinality in the following case:
- Value V is of type T, which has a cardinality for datatype property P1, but no cardinality for datatype property P2.
- V has P1 with object `"foo"`, and P2 with object `"foo"`.

The cardinality for P1 will match the rule's pattern for verifying P2, so no violation will be found.

The rule is written this way to allow the case where T has a cardinality for a superproperty of P1, rather than a cardinality for P1 itself.

Consider disallowing this case and making the rule more stringent to avoid this problem.

**Comment by seakayone** [comment]
This issue has been inactive for a significant time, so we’re closing it for now. If it’s still relevant, feel free to reopen.
