### ISSUE TITLE
Keep an eye on SHACL

### ISSUE THREAD

**Issue by benjamingeer** [dasch-swiss/dsp-api#249]
[Shapes Constraint Language (SHACL)](http://www.w3.org/TR/shacl/) is a language for validating RDF graphs against a set of conditions.

**Comment by musicEnfanthen** [comment]
Since July 2017 SHACL is a W3C recommendation.

Some other interesting links:

- https://www.linkedin.com/pulse/meet-shacl-next-owl-kurt-cagle

- https://semanticarts.com/blog/rdf-shapes/

**Comment by seakayone** [comment]
We are currently integrating SHACL validation in dsp-tools. 
This issue has been inactive for a significant time, so we’re closing it for now. If it’s still relevant, feel free to reopen.
