### ISSUE TITLE
Display of nodes for hierachical list and selections

### ISSUE THREAD

**Issue by mrivoal** [dasch-swiss/dsp-api#321]
This is an opened question.

I am wondering whether the **current default display for selections' and hierarchical lists' nodes** is the most convenient.

![capture d ecran 2016-11-11 a 11 24 03 copie](https://cloud.githubusercontent.com/assets/17294309/20219191/86302566-a828-11e6-8399-6dda31791508.png)

It is my understanding that, for **selections**, the first node of the list is selected by default. 

For **hlist**, the first node of the list is also selected by default, but the first subnode is left blank. I assume it is so in order to let the user select the first node without going further if the 1st level of the hierarchy is where he wants to stop.

If the user doesn't want any value for a property with a `knora-base:objectClassConstraint` on `knora-base:ListValue` , he will have to delete the field by clicking on the red cross because he can't leave the first entry for a list blank . But **properties for this value do not behave like others**: if you don't want any value to be entered for a `knora-base:TextValue`, then you can just leave it blank and create the resource as is (provided that the cardinality allows it). 

My concern is about the errors the current display could result in for users. **Shouldn't the behaviour for all the values be the same?** What about displaying the first node of a list as blank so that users can simply leave it like this if nothing is to be entered in this field instead of having him deleting it?

**Comment by benjamingeer** [comment]
I agree with you. There are lots of things that aren't user-friendly in the old SALSAH. But the project to make SALSAH user-friendly is called SALSAH 2. If we try to fix all the annoyances (as opposed to bugs) in the old SALSAH, we're going to delay Knora and SALSAH 2. Unless Lukas disagrees with me, I think we have to leave things like this as they are.

**Comment by mrivoal** [comment]
We could work with it as is. But what should I do then to be sure this issue is taken into account for Salsah 2.0?

**Comment by benjamingeer** [comment]
I see now that all the issues about SALSAH 2 are just tagged with the "frontend (salsah)" label. Perhaps we should have a "salsah2" issue label to distinguish between problems with the current SALSAH and requirements for SALSAH 2.

**Comment by sofiag** [comment]
Dear Marion,

Together with André, we are working on the new GUI for Salsah 2, and I am now starting to think of the design and content of the ontology GUI. We have Salsah 2 in a separate git repository. It is maybe best to add these issues there, as requirements for the new GUI.

Best,
Sofia




——————————————————
Dr. Sofia Georgakopoulou
Digital Humanities Lab
University of Basel
Bernoullistrasse 32,
4056 Basel, Switzerland
tel: +41 61 207 09 09
email: s.georgakopoulou@unibas.ch
——————————————————

**Comment by mrivoal** [comment]
Hello Sofia, 

Thanks for the suggestion. I just created the very first issue on Salsah 2 repository :-)

**Comment by jroland01** [comment]
Hi Sofia -

I am not able to see the Salsah 2 git repository from the list in dhlab-basel ?

Another question : Is there a way to access the latest wireframes, screens, designs for Salsah 2 for comment purposes (if, and when feedback is requested by you) ?

Kind regards, Julien

**Comment by mrivoal** [comment]
@jroland01 Tu y accèdes ici:
https://github.com/dhlab-basel/Salsah

**Comment by sofiag** [comment]
Dear Julian,

You can find some mockups in the repository here:
Salsah <https://github.com/dhlab-basel/Salsah>/docs <https://github.com/dhlab-basel/Salsah/tree/develop/docs>/rst <https://github.com/dhlab-basel/Salsah/tree/develop/docs/rst>/salsah2 <https://github.com/dhlab-basel/Salsah/tree/develop/docs/rst/salsah2>/components <https://github.com/dhlab-basel/Salsah/tree/develop/docs/rst/salsah2/components>/figures/

Best,
Sofia

——————————————————
Dr. Sofia Georgakopoulou
Digital Humanities Lab
University of Basel
Bernoullistrasse 32,
4056 Basel, Switzerland
tel: +41 61 207 09 09
email: s.georgakopoulou@unibas.ch
——————————————————

**Comment by jroland01** [comment]
OK. Thanks a lot !

Let me know if you need usability feedback, comments on some of the mockups.

Julien

**Comment by seakayone** [comment]
This issue has been inactive for a significant time, so we’re closing it for now. If it’s still relevant, feel free to reopen.
