### ISSUE TITLE
Is Sipi managing all external files (including non-image files)?

### ISSUE THREAD

**Issue by mrivoal** [dasch-swiss/dsp-api#322]
Another question regarding the way files are handled by Salsah/Knora.

When trying to create a resource with a `knora-base:hasFileValue` property, regardless of the file format I am trying to upload, I get a "call to Sipi failed" error.
 
I should probably add that we haven't been able to have Sipi work fine yet.

So, is Sipi handling all external files?

**Comment by benjamingeer** [comment]
> So, is Sipi handling all external files?

Yes.

> I should probably add that we haven't been able to have Sipi work fine yet.

"It doesn't work" is too vague, we can't do anything with that. Are there any problems other than the ones you've already reported? If so, please create issues on the Sipi GitHub repository and give details.

> I get a "call to Sipi failed" error.

Please give more details: is there a more detailed error message on the Knora console? Does Sipi output an error message on the console?

**Comment by tobiasschweizer** [comment]
call to sipi failed is triggered in case sipi sends back a non successful http status or if it is not running at all

**Comment by loicjaouen** [comment]
@benjamingeer yes, it is a bit too vague, I see that there is some new commits, I will try to update it and fully report the problems. Do we know now if we should run it as 'root' or not?

**Comment by benjamingeer** [comment]
You only need to run it as root if you want it to change (by itself) to run as some other user after it starts, as specified in the config file. I don't recommend doing this. Just start it as whatever normal user you want to run as. However, it seems that there's a bug that's making Sipi incorrectly say it needs to be run as root: https://github.com/dhlab-basel/Sipi/issues/72

**Comment by seakayone** [comment]
This issue has been inactive for a significant time, so we’re closing it for now. If it’s still relevant, feel free to reopen.
