### ISSUE TITLE
Add a data type for storing durations

### ISSUE THREAD

**Issue by mrivoal** [dasch-swiss/dsp-api#329]
I read in #327 that you are planning to introduce a new` knora-base:DateTimeValue`. I think it could be a good thing (in fact, some researchers have already expressed this need).

But how are we supposed to express a duration (without any interest in the date) to express the duration of a movie, audio recording, etc.? I don't think this value exists yet (and we need it)?

**Comment by benjamingeer** [comment]
The duration of a movie or audio recording is stored in `AudioFileValue` and `MovingImageFileValue`, in the property `duration`.

If you want to express a point or range in time relative to the beginning of an audio or video file, you can use `IntervalValue`.

**Comment by mrivoal** [comment]
Yes, but in this case, there will be no `AudioFileValue` or `MovingImageFileValue`. 

The resource is a `knora-base:Resource`, called "Sequence" but with no file attached. The team needs to express the duration of a program's sequence in HH:MM:SS in absolute values, amongst other properties, such as the journalists involved, the topics discussed, etc. 

Is there currently a way to handle this within Knora and Salsah?

**Comment by benjamingeer** [comment]
We could add a `DurationValue` type, storing an `xsd:duration`:

https://www.w3.org/TR/xmlschema11-2/#duration

**Comment by mrivoal** [comment]
That would be great. 

By the way, if you look at `knora-base:duration`, the `objectDatatypeConstraint` is on `xsd:decimal`. Is this right?

**Comment by benjamingeer** [comment]
Yes, I believe it's a value in seconds, which can be fractional.

**Comment by benjamingeer** [comment]
Maybe `knora-base:duration` should store an `xsd:duration`, though.

**Comment by mrivoal** [comment]
Just to let you... We will probably need this to be implemeted for the very first project we will launch on Knora. They are planning to begin data input around the 15th of january. Do you with at that time a  `DurationValue` type could be implemented in Knora + in the GUI?

**Comment by benjamingeer** [comment]
We might be able to do it by then. Let me check with Lukas and get back to you.

**Comment by seakayone** [comment]
This issue has been inactive for a significant time, so we’re closing it for now. If it’s still relevant, feel free to reopen.
