### ISSUE TITLE
Add support for Geonames

### ISSUE THREAD

**Issue by tobiasschweizer** [dasch-swiss/dsp-api#335]
In the old Salsah, we support a value type geonames.

This type exists in knora-base, but is not implemented (resolving a geoname using their API).

Who is going to do this and when?

I am aware of the fact that this is a dangerous question ... (because you could say I should do it since I am asking).

**Comment by benjamingeer** [comment]
Since you've assigned this to all of us, I guess the question is answered, so I can close this issue.

**Comment by benjamingeer** [comment]
What exactly did it do in the old SALSAH?

**Comment by subotic** [comment]
I think that @kilchenmann implemented this in the "old" Salsah.

**Comment by mrivoal** [comment]
Just saying: I think it should be implemented in Salsah 2.0. But we might want to support geodata more broadly. Having a property for storing coordinates would be a good start; but we could go as far as storing geodata itself which is, admittedly, much more tricky : [http://data.ign.fr/data.html ](url).

But what are your thoughts as for **Salsah 1.5**? Will geonames be supported or not?

**Comment by tobiasschweizer** [comment]
I am working on V2 now. I think we absolutely need to implement GeoNames.

**Comment by loicjaouen** [comment]
For info: here is the first mockup to make a search form we did some time ago (it doesn't include suggested improvements that we collected):
https://platec.unil.ch/test/xtdsrch/search

You can click on `Persons` and `Works` to list the items you can play with.  
The simple search, select `Person` or `Work` depending what you look for, type `ez` press `search` and you get a list of results.  
The extended search allows to do search by exploring the graph, like saying `works from authors who published in 1912` (change it to 1916 and the final result changes quite a bit):
![extended search clickable demo](https://cloud.githubusercontent.com/assets/3933654/24396548/dd6e38c2-13a3-11e7-8a24-19b2330edcb2.png)

**Comment by lrosenth** [comment]
In addition, we should also propvide for Google geolocations. Man y people rely for this on google (which includes – taht’s interesting – also historical geo-names!

Lukas

On 28 Mar 2017, at 10:48, Loïc Jaouen <notifications@github.com<mailto:notifications@github.com>> wrote:


For info: here is the first mockup to make a search form we did some time ago (it doesn't include suggested improvements that we collected):
https://platec.unil.ch/test/xtdsrch/search

You can click on Persons and Works to list the items you can play with.
The simple search, select Person or Work depending what you look for, type ez press search and you get a list of results.
The extended search allows to do search by exploring the graph, like saying works from authors who published in 1912 (change it to 1916 and the final result changes quite a bit):
[extended search clickable demo]<https://cloud.githubusercontent.com/assets/3933654/24396548/dd6e38c2-13a3-11e7-8a24-19b2330edcb2.png>

**Comment by musicEnfanthen** [comment]
Just my 5 cents as we also need standardized geodata in Webern:

When it comes to historical geodata we should seriously take into consideration the ["Geschichtliches Ortsverzeichnis"](http://wiki-de.genealogy.net/GOV) that provides a model to represent historical administrative location structures with semantic technologies. 

There is a very good overview on different location modelling approaches (including GOV) in this article by @jze: Jesper Zedlitz/Norbert Luttenberger: "A Survey on Modelling Historical Administrative Information on the Semantic Web", in: _International Journal on Advances in Internet Technology_ 7/3 & 4 (2014), pp. 218–231 ([PDF](http://www.iariajournals.org/internet_technology/inttech_v7_n34_2014_paged.pdf)).

**Comment by mrivoal** [comment]
Back again with this issue but with a simple question :  

**Are we going to support Geonames in Salsah 1.5?** 

Without opening Pandora box regarding geodata support, I think it could be temporarily satisafying. 

However, it doesn't work yet, right? Because I saw that the geoname values were commented out in `anything-onto.ttl`.  I tested it anyway but I can't create a `Thing` resource with a geonameValue, I got an error saying:

```
error
Bad Request
The request content was malformed:
Expected Collection as JsArray, but got {"value":"gnid:2988507"}
```

So, I guess there is something wrong with it? Hence, the simple question above.

**Comment by tobiasschweizer** [comment]
As far as I remember, the GUI does not support Geonames.

I have a similar issue regarding IAF/GND to identify persons. Do we need to make a new value type for IAF/GND like we did for Geoname? Knora needs to know how to resolve a given IAF/GND identifier.

**Comment by mrivoal** [comment]
Ok, so I will just leave `GeonameValue` aside for the moment.

What is the link/difference between IAF/GND identifier and [VIAF](https://viaf.org/)? I see the Deutsche Nationalbibliothek contributes to VIAF, as well as the Bibliothèque Nationale de France. Does it makes VIAF susceptible to cover the needs of a broader audience?

If Knora was able to resolve those identifiers, I guess that would be great, but we will need to decide together what would be the identifiers and authority files supported. Until then, I also decided to store the information in a `TextValue`.

**Comment by tobiasschweizer** [comment]
IAF/GND is provided by the German national library, VIAF is more an international project I believe. But IAF/GND links to VIAF.

Knora needs to know how to resolve these identifiers, but I am not comfortable with adding a new value type to `knora-base` each time we want to add a new kind of identifier. Maybe there is a way to make this more generic by providing a resolver when you define the property (so that would not be a thing assigned to the value type itself).

**Comment by musicEnfanthen** [comment]
Yes, VIAF combines and links together many international norm data sets. But it would be good not to be exclusive, so any project could use the norm data identifiers they want or have to.

What about allowing  `hasExtResValue` not only on `ExternalResource` but also on `Resource` as kind of a generic resolver value ?


```
###  http://www.knora.org/ontology/knora-base#ExternalResource

:ExternalResource rdf:type owl:Class ;

                  rdfs:subClassOf :Resource ,
                                  [ rdf:type owl:Restriction ;
                                    owl:onProperty :hasExtResValue ;
                                    owl:cardinality "1"^^xsd:nonNegativeInteger
                                  ] ;

                  rdfs:label "Externe Ressource"@de ,
                             "External Resource"@en ,
                             "Ressource Externe"@fr ,
                             "Risorsa esterna"@it ;

rdfs:comment "Represents a proxy for an object stored by an external provider"@en .
```

```
###  http://www.knora.org/ontology/knora-base#hasExtResValue

:hasExtResValue rdf:type owl:ObjectProperty ;

                rdfs:label "hat externen Wert"@de ,
                           "has external Value"@en ,
                           "a valeur externe"@fr ,
                           "ha valore esterno"@it ;

                :objectClassConstraint :ExternalResValue ;

                :subjectClassConstraint :ExternalResource ;

rdfs:subPropertyOf :hasValue .
```

```
###  http://www.knora.org/ontology/knora-base#ExternalResValue

:ExternalResValue rdf:type owl:Class ;

                  rdfs:subClassOf :Value ,
                                  [ rdf:type owl:Restriction ;
                                    owl:onProperty :extResId ;
                                    owl:cardinality "1"^^xsd:nonNegativeInteger
                                  ] ,
                                  [ rdf:type owl:Restriction ;
                                    owl:onProperty :extResProvider ;
                                    owl:cardinality "1"^^xsd:nonNegativeInteger
                                  ] ,
                                  [ rdf:type owl:Restriction ;
                                    owl:onProperty :extResAccessInfo ;
                                    owl:cardinality "1"^^xsd:nonNegativeInteger
] .
```

where in `extResProvider` or `ExtResAccessInfo` you could provide the information about the Resolver?

But maybe I'm missing something.

**Comment by tobiasschweizer** [comment]
The idea behind `:ExternalResource` is that of a proxy resource. This allows you to annotate a non Knora resource (the `:ExternalResource` is annotated instead of the external resource you do not have writing access to).

With the `:ExternalResource` all the information is stored to retrieve the external resource from a third-party provider.

This is indeed similar to what we want to do with Geonames or GND. It would be very nice to have a generic type of an external identifier with information how to retrieve this information (e.g. resolve a GND identifier).

**Comment by mrivoal** [comment]
I'm coming back to the GND, VIAF, BNF topic. 

[ISNI](http://www.isni.org/) is an even wider consortium and an ISO standard for persons and organizations. Data can be retrieved in RDF (and XML).  

More details on ISNI and its links to VIAF and ORCID: http://www.bnf.fr/fr/professionnels/isni_informer/s.isni.html

**Comment by hanscools** [comment]
What about representing a standard code, e.g. an ISBN (= ISO 2108) as a datatyped literal, e.g. `"978-1-449-36793-0"^^standard:isbn` OR `"978-1-449-36793-0"^^iso:2108` OR `"978-1-449-36793-0"^^iso:isbn`? E.g.
```
@prefix iso: <http://www.knora.org/ontology/iso-standards#>. # e.g.
iso:isbn
       a rdfs:Datatype;
       rdfs:label "ISO 2108 or ISBN datatype"@en;
       rdfs:comment """Datatype to type an ISO 2108 or ISBN code."""@en.

## an instance:
:bookX
       a :Book;
       :hasISBN <http://data.knora.org/0cn8285554d5/values/3ca6641ced0f04>;
       :hasTitel <http://data.knora.org/0cb8285554d5/values/3caf141ced0f04>;
       :hasAuthor <http://viaf.org/viaf/someNumberX>;
       :hasPublisher <http://viaf.org/viaf/someNumberY>.
<http://data.knora.org/0cn8285554d5/values/3ca6641ced0f04>
       a knora-base:StandardValue; # proposal
       knora-base:valueHasString "978-1-449-36793-0"^^iso:isbn.
<http://data.knora.org/0cb8286054d5/values/3caf141ced0f04>
       a knora-base:TextValue;
       knora-base:valueHasString "Learning Scala: Practical Functional Programming for the JVM"@en.
```
Idem for other ISOs, e.g. for countries e.g. `"ch"^^iso:3166-1-alpha-2`, as used in Geonames. E.g.

```
@prefix iso: <http://www.knora.org/ontology/iso-standards#>. # e.g.
iso:3166-1-alpha-2
       a rdfs:Datatype;
       rdfs:label "ISO 3166-1-alpha-2 datatype"@en;
       rdfs:comment """Datatype to type an ISO 3166-1-alpha-2 country code."""@en.

## an instance:
<http://sws.geonames.org/2658434/>
      a <http://www.geonames.org/ontology#Feature> ;
      rdfs:isDefinedBy <http://sws.geonames.org/2658434/about.rdf> ;
      ns0:name "Switzerland" ;
      ns0:alternateName "ස්විස්ටර්ලන්තය"@si; # one of many, but the nicest :)
      ns0:countryCode "CH" ; # can be replaced by "ch"^^iso:3166-1-alpha-2
      ns0:population "7581000" ;
      geo:lat "47.00016" ;
      geo:long "8.01427" ;
      ns0:parentFeature <http://sws.geonames.org/6255148/> ;
      ns0:childrenFeatures <http://sws.geonames.org/2658434/contains.rdf> ;
      ns0:neighbouringFeatures <http://sws.geonames.org/2658434/neighbours.rdf> ;
      ns0:locationMap <http://www.geonames.org/2658434/switzerland.html> ;
      ns0:wikipediaArticle <http://en.wikipedia.org/wiki/Switzerland> ;
      rdfs:seeAlso <http://dbpedia.org/resource/Switzerland> .
```
I contacted the responsible person  Marc Wick ‎[marc@geonames.org]‎ .
They don't have a sparql endpoint or an rdf triple store. The rdf documents are generated from a postgres relational database.
E.g. for the Lombardus project I create an RDF dataset with all needed country and city graphs.

**Comment by lrosenth** [comment]
Yes, Thiscould be the way to go regarding ISBN.

Regarding geo codes, I’m still not satisfied with genomes.org<http://genomes.org>. I’m thinking of a more generic approach. And it’s a pitty that geonames does not have a SPARQL endpoint…

Thanks, Hans,
Lukas

Am 08.06.2017 um 00:45 schrieb hanscools <notifications@github.com<mailto:notifications@github.com>>:


What about representing a standard code, e.g. an ISBN (= ISO 2108) as a datatyped literal, e.g. "978-1-449-36793-0"^^standard:isbn OR "978-1-449-36793-0"^^iso:2108 OR "978-1-449-36793-0"^^iso:isbn? E.g.

@prefix iso: <http://www.knora.org/ontology/iso-standards#>. # e.g.
iso:isbn
       a rdfs:Datatype;
       rdfs:label "ISO 2108 or ISBN datatype"@en;
       rdfs:comment """Datatype to type an ISO 2108 or ISBN code."""@en.

## an instance:
:bookX
       a :Book;
       :hasISBN <http://data.knora.org/0cn8285554d5/values/3ca6641ced0f04>;
       :hasTitel <http://data.knora.org/0cb8285554d5/values/3caf141ced0f04>;
       :hasAuthor <http://viaf.org/viaf/someNumberX>;
       :hasPublisher <http://viaf.org/viaf/someNumberY>.
<http://data.knora.org/0cn8285554d5/values/3ca6641ced0f04>
       a knora-base:StandardValue; # proposal
       knora-base:valueHasString "978-1-449-36793-0"^^iso:isbn.
<http://data.knora.org/0cb8286054d5/values/3caf141ced0f04>
       a knora-base:TextValue;
       knora-base:valueHasString "Learning Scala: Practical Functional Programming for the JVM"@en.


Idem for other ISOs, e.g. for countries e.g. "ch"^^iso:3166-1-alpha-2, as used in Geonames. E.g.

@prefix iso: <http://www.knora.org/ontology/iso-standards#>. # e.g.
iso:3166-1-alpha-2
       a rdfs:Datatype;
       rdfs:label "ISO 3166-1-alpha-2 datatype"@en;
       rdfs:comment """Datatype to type an ISO 3166-1-alpha-2 country code."""@en.

## an instance:
<http://sws.geonames.org/2658434/>
      a <http://www.geonames.org/ontology#Feature> ;
      rdfs:isDefinedBy <http://sws.geonames.org/2658434/about.rdf> ;
      ns0:name "Switzerland" ;
      ns0:alternateName "ස්විස්ටර්ලන්තය"@si; # one of many, but the nicest :)
      ns0:countryCode "CH" ; # can be replaced by "ch"^^iso:3166-1-alpha-2
      ns0:population "7581000" ;
      geo:lat "47.00016" ;
      geo:long "8.01427" ;
      ns0:parentFeature <http://sws.geonames.org/6255148/> ;
      ns0:childrenFeatures <http://sws.geonames.org/2658434/contains.rdf> ;
      ns0:neighbouringFeatures <http://sws.geonames.org/2658434/neighbours.rdf> ;
      ns0:locationMap <http://www.geonames.org/2658434/switzerland.html> ;
      ns0:wikipediaArticle <http://en.wikipedia.org/wiki/Switzerland> ;
      rdfs:seeAlso <http://dbpedia.org/resource/Switzerland> .


I contacted the responsible person Marc Wick ‎[marc@geonames.org<mailto:marc@geonames.org>]‎ .
They don't have a sparql endpoint or an rdf triple store. The rdf documents are generated from a postgres relational database.
E.g. for the Lombardus project I create an RDF dataset with all needed country and city graphs.

**Comment by benjamingeer** [comment]
Maybe this needs to be reconsidered in light of #1187.
