### ISSUE TITLE
Parsing errors due to not well formed XML should be caught in StandoffUtil

### ISSUE THREAD

**Issue by benjamingeer** [dasch-swiss/dsp-api#346]
`StandoffUtil.xml2TextWithStandoff` should catch these and throw a Knora-specific exception.

**Comment by benjamingeer** [comment]
cc @tobiasschweizer

**Comment by seakayone** [comment]
This issue has been inactive for a significant time, so we’re closing it for now. If it’s still relevant, feel free to reopen.
