### ISSUE TITLE
Limit the number of incoming links to a resource via a particular property

### ISSUE THREAD

**Issue by benjamingeer** [dasch-swiss/dsp-api#353]
Use case from @loicjaouen and @mrivoal :

* An artist resource can have links to several place-of-activity resources.
* A place-of-activity resource belongs to (has a link from) a single artist resource.
* When an artist resource is marked as deleted, its place-of-activity resources must also be marked as deleted.

I think this could be done by creating a property in `knora-base` called something like `hasDependentResource`, which could be checked in SPARQL queries and in GraphDB consistency checks to enforce these rules.

**Comment by seakayone** [comment]
This issue has been inactive for a significant time, so we’re closing it for now. If it’s still relevant, feel free to reopen.
