### ISSUE TITLE
Fix inconsistencies in SALSAH export script

### ISSUE THREAD

**Issue by benjamingeer** [dasch-swiss/dsp-api#62]
The export script produces some inconsistencies in the Incunabula ontology and data, and I haven't figured out how to deal with them.
#### In incunabula:book
- `title` has `owl:cardinality 1`, but book `http://data.knora.org/e41ab5695c` has two titles (so the cardinality could be `owl:minCardinality 1`).
- `publoc` has `owl:cardinality 1`, but book `http://data.knora.org/de6d83112e04` has no `publoc` (so the cardinality could be `owl:maxCardinality 1`).
- `publisher` has `owl:maxCardinality 1`, but book `http://data.knora.org/9311a421b501` has two publishers (so the cardinality could be `owl:minCardinality 0`).
#### In incunabula:page
- `pagenum` has `owl:cardinality 1`, but page `http://data.knora.org/f84653d34004` has no `pagenum` (so the cardinality could be `owl:maxCardinality 1`).
- `seqnum` has `owl:cardinality 1`, but page `http://data.knora.org/f84653d34004` has no `seqnum` (so the cardinality could be `owl:maxCardinality 1`).
#### In incunabula:Sideband
- `description` has `owl:cardinality 1`, but sideband `http://data.knora.org/684a7a4ec5d7` has no `description` (so the cardinality could be `owl:maxCardinality 1`).
### Property subject class constraints
- `incunabula:description` has `knora-base:subjectClassConstraint :Sideband`, but in the exported data, its subject is sometimes a `:book` or a `:page`.
- `incunabula:citation` has `knora-base:subjectClassConstraint :page`, but in the exported data, its subject can be either a `:book` or a `:page`.
### Reference to nonexistent resource

Page `http://data.knora.org/9374cc0a4f03` says it has a left sideband `http://data.knora.org/bb4a4d4758e722`, but that sideband doesn't exist. If I view the page in the old SALSAH (page `l8r` in _[Das] Narrenschiff (dt.)_), it's clear that there's no sideband on that page.
### Incorrect references to external resources

`http://data.knora.org/c30e76e55204` is a `knora-base:ExternalResource`. It should have a `knora-base:hasExtResValue` property pointing to a `knora-base:ExternalResValue`, but instead it has `knora-base:extResId` and `knora-base:extResProvider`, each of which point to a `knora-base:ExternalResValue`. The two instances of `knora-base:ExternalResValue` have the same contents.

The other external resources have the same problem.
### Regions without isRegionOf

These regions have no `isRegionOf` (required by the cardinality on `Region`):
- `http://data.knora.org/c9905d015030`
- `http://data.knora.org/8e96ec3b5030`
- `http://data.knora.org/d8e282a38b32`
- `http://data.knora.org/707f8edf3935`
- `http://data.knora.org/d44533274407`

It makes no sense to have a region that isn't a region of something, so probably these regions should be excluded from the export.
### Page without isPartOf

The page `http://data.knora.org/3c94b29fb90f02` has no `incunabula:partOf` (required by the cardinality on `page`). It makes no sense to have a page that isn't part of a book, so probably this page should be excluded from the export.
### Off by one

In `incunabula:seqnum`, `valueHasString` is different from `valueHasInteger`. For example, in page `http://data.knora.org/9374cc0a4f03`, the `seqnum` is `http://data.knora.org/9374cc0a4f03/values/ac5f87e52f0d`. Its `valueHasInteger` is `177`, but its `valueHasString` is `176`.

**Comment by lrosenth** [comment]
Hi Ben,

Thanks a lot!! We'll go after these problems. I'm definitwl feeling better now (still a bit tird from tha antibiotics).
I think next week I'm back to my old energy :-)

Thanks a lot, best regards,
Lukas

Von meinem iPad gesendet

Am 02.03.2016 um 20:30 schrieb Benjamin Geer <notifications@github.com<mailto:notifications@github.com>>:


The export script produces some inconsistencies in the Incunabula ontology and data, and I'm haven't figured out how to deal with them.

Cardinalities
In incunabula:book

  *   title has owl:cardinality 1, but book http://data.knora.org/e41ab5695c has two titles (so the cardinality could be owl:minCardinality 1).
  *   publoc has owl:cardinality 1, but book http://data.knora.org/de6d83112e04 has no publoc (so the cardinality could be owl:maxCardinality 1).
  *   publisher has owl:maxCardinality 1, but book http://data.knora.org/9311a421b501 has two publishers (so the cardinality could be owl:minCardinality 0).

In incunabula:page

  *   pagenum has owl:cardinality 1, but page http://data.knora.org/f84653d34004 has no pagenum (so the cardinality could be owl:maxCardinality 1).
  *   seqnum has owl:cardinality 1, but page http://data.knora.org/f84653d34004 has no pagenum (so the cardinality could be owl:maxCardinality 1).

In incunabula:Sideband

  *   description has owl:cardinality 1, but sideband http://data.knora.org/684a7a4ec5d7 has no description (so the cardinality could be owl:maxCardinality 1).

Property subject class constraints

  *   incunabula:description has knora-base:subjectClassConstraint :Sideband, but in the exported data, its subject is sometimes a :book or a :page.
  *   incunabula:citation has knora-base:subjectClassConstraint :page, but in the exported data, its subject can be either a :book or a :page.

Reference to nonexistent resource

Page http://data.knora.org/9374cc0a4f03 says it has a left sideband http://data.knora.org/bb4a4d4758e722, but that sideband doesn't exist. If I view the page in the old SALSAH (page l8r in [Das] Narrenschiff (dt.)), it's clear that there's no sideband on that page.

Incorrect references to external resources

http://data.knora.org/c30e76e55204 is a knora-base:ExternalResource. It should have a knora-base:hasExtResValue property pointing to a knora-base:ExternalResValue, but instead it has knora-base:extResId and knora-base:extResProvider, each of which point to a knora-base:ExternalResValue. The two instances of knora-base:ExternalResValue have the same contents.

The other external resources have the same problem.

Regions without isRegionOf

These regions have no isRegionOf (required by the cardinality on Region):

  *   http://data.knora.org/c9905d015030
  *   http://data.knora.org/8e96ec3b5030
  *   http://data.knora.org/d8e282a38b32
  *   http://data.knora.org/707f8edf3935
  *   http://data.knora.org/d44533274407

It makes no sense to have a region that isn't a region of something, so probably these regions should be excluded from the export.

Page without isPartOf

The page http://data.knora.org/3c94b29fb90f02 has no incunabula:partOf (required by the cardinality on page). It makes no sense to have a page that isn't part of a book, so probably this page should be excluded from the export.

Off by one

In incunabula:seqnum, valueHasString is different from valueHasInteger. For example, in page http://data.knora.org/9374cc0a4f03, the seqnum is http://data.knora.org/9374cc0a4f03/values/ac5f87e52f0d. Its valueHasInteger is 177, but its valueHasString is 176.

**Comment by benjamingeer** [comment]
Here's a problem in `knora-base`:

`ListNode` requires the property `listNodePosition`, but if the list node is a root node, it doesn't have this property. Should we make the property optional, add a dummy `listNodePosition` to the root node, or do something else?

**Comment by benjamingeer** [comment]
In `knora-base`, `ListNode` required these properties:

* `listNodePosition`
* `listNodeName`
* `hasRootNode`

But these properties aren't relevant if the node is the root node. I made them optional.

**Comment by benjamingeer** [comment]
This is wrong in the export of the dokubib ontology:

```
:lastname rdf:type owl:ObjectProperty ;
          rdfs:subPropertyOf foaf:lastName ;
          knora-base:objectClassConstraint knora-base:TextValue ;
```

This can't work, because this property isn't a subproperty of `knora-base:hasValue`. I don't know whether this is because of a bug in the export script or in the JSON configuration file. I think what would be correct would be this:

```
:lastname rdf:type owl:ObjectProperty ;
          rdfs:subPropertyOf foaf:lastName ,
                             knora-base:hasValue ;
```

**Comment by benjamingeer** [comment]
There are also resources with text values containing what seems to be a MySQL ID in `valueHasString`. Examples:

* `<http://data.knora.org/c5cf5a2bc6be>` has a `hasComment` pointing to a text value containing `213506` in `valueHasString`.
* `<http://data.knora.org/362e61bda5d7>` has a `description` pointing to a text value containing `271279` in `valueHasString`.

**Comment by benjamingeer** [comment]
The export script misspells a permission: `knora-base:hasChangeRightsPermission` is misspelled as `knora-base:hasChangeRightsPermisson`.
