### ISSUE TITLE
Creating file information for Sipi

### ISSUE THREAD

**Issue by tobiasschweizer** [dasch-swiss/dsp-api#64]
In Sipi responder's method `getFileInfoForSipiV1`, a `SipiFileInfoGetResponseV1` is created and returned containing the permissions the user has on the file and the path/name of the file.

So this allows Sipi to send a fileValueIri to Knora and get the user's permissions on the file and also the actual file name (so Sipi can find it on the file system and read it).

This happens after the client has sent a IIIF-URL to the Sipi server naming a fileValueIri. Why would Sipi responder return another URL to access the file which it was already called with by the client?  

``` scala
fileValueV1: FileValueV1 => valueUtilV1.makeSipiFileGetUrlFromFileValueV1(fileValueV1)

...


    /**
      * Creates a URL for accessing a file via Sipi. // TODO: implement this correctly.
      *
      * @param fileValueV1 the file value that the URL will point to.
      * @return a Sipi URL.
      */
    // TODO: if this is a StillImageFileValue, create a IIIF URL
    def makeSipiFileGetUrlFromFileValueV1(fileValueV1: FileValueV1): String = {
        makeSipiFileGetUrlFromFilename(fileValueV1.internalFilename)
    }

    /**
      * Creates a URL for accessing a file via Sipi. // TODO: implement this correctly.
      *
      * @param filename the name of the file that the URL will point to.
      * @return a Sipi URL.
      */
    def makeSipiFileGetUrlFromFilename(filename: String): String = {
        s"${settings.sipiUrl}/$filename"
    }

```

I think we have to different cases here:
1. Knora creates a IIIF-URL for the client to access an image asking Sipi
2. Sipi has to ask Knora about the user's permissions on the file and about the internal filename in case it got a fileValueIri in the IIIF-URL (possibly, this isn't even necessary, as Knora could directly put the file's name in it, also making use of the prefix to declare the project)

**Comment by benjamingeer** [comment]
I don't understand the question. The methods you quoted above are in `ValueUtilV1`, not in the Sipi responder. These methods are meant to be used by the resources responder and the search responder, which need to generate IIIF (and other) URLs for files that can be retrieved from Sipi. That's use case (1). These methods don't have anything to do with use case (2), as far as I can see, so I don't understand what you're asking.

**Comment by tobiasschweizer** [comment]
Please have a look at Sipi responder:

```scala
private def getFileInfoForSipiV1(fileValueIri: IRI, userProfile: UserProfileV1): Future[SipiFileInfoGetResponseV1] = {
        for {
            sparqlQuery <- Future(queries.sparql.v1.txt.getFileValue(fileValueIri).toString())
            queryResponse <- (storeManager ? SparqlSelectRequest(sparqlQuery)).mapTo[SparqlSelectResponse]
            rows = queryResponse.results.bindings
            valueProps = valueUtilV1.createValueProps(fileValueIri, rows)
            valueV1 = valueUtilV1.makeValueV1(valueProps)
            path = valueV1 match {
                case fileValueV1: FileValueV1 => valueUtilV1.makeSipiFileGetUrlFromFileValueV1(fileValueV1)
                case otherValue => throw InconsistentTriplestoreDataException(s"Value $fileValueIri is not a FileValue, it is an instance of ${otherValue.valueTypeIri}")
            }
            permissionCode = PermissionUtilV1.getUserPermissionV1WithValueProps(fileValueIri, valueProps, userProfile)
        } yield SipiFileInfoGetResponseV1(
            permissionCode = permissionCode,
            path = permissionCode.map(_ => path)
        )
    }
```
Here, `valueUtilV1.makeSipiFileGetUrlFromFileValueV1` gets called producing an image-URL returned to Sipi as part of `SipiFileInfoGetResponseV1`. The same method from `ValueUtilV1`is used to produce the IIIF-URLs for the client in the first place.

I am saying that the two unrelated use cases are intermingled here which isn't correct. I am about to change that in a new branch.

**Comment by benjamingeer** [comment]
Yes, you're right! I don't know what `path` should actually be in this case.

**Comment by tobiasschweizer** [comment]
Ok, that's all I needed to know :-) I got simply got confused when I saw this call in Sipi responder so I wanted to clarify it ;-)
