### ISSUE TITLE
typescript interface test data (brush-up)

### ISSUE THREAD

**Issue by loicjaouen** [dasch-swiss/dsp-api#678]
in #673 @tobiasschweizer pointed out errors in when running the test:
```bash
make jsonformattest
```

While modifying the salsah 1.5 code to fit the new IRI schema, I did the same on the interface and test data:
e6580fbdfe8c29b0a021811b74325c9271e77fc3
68f12d98e32a537799150d63a1bd37d6ca63ea9b
2d68024950b0a16c2eb817fa33e393526a621a97

However, even if the test passes now, some other files in [salsah/src/typescript_interfaces/sampleRequests](https://github.com/dhlab-basel/Knora/tree/develop/salsah/src/typescript_interfaces/sampleRequests) will need a brush-up.

**Comment by tobiasschweizer** [comment]
`make jsonformattest` is not supposed to be a test in the proper sense like our E2E or the unit tests. It should just ensure that the API's documentation is accurate. Obviously when changing things in the API response formts, both the sample responses and the documentation have to be updated.

I propose that @subotic updates the API documentation and the sample responses as he works on the project API. @kilchenmann should also be kept informed (SALSAH GUI).
