### ISSUE TITLE
`/v1/resources`'s `lastmod` is always `0000-00-00 00:00:00`

### ISSUE THREAD

**Issue by loicjaouen** [dasch-swiss/dsp-api#740]
When requesting a resource, it's `lastmod` field is left *blank* as shown in the current tests:

- search github for `lastmod`: https://github.com/dhlab-basel/Knora/search?utf8=%E2%9C%93&q=lastmod&type=
- data spec: https://github.com/dhlab-basel/Knora/blob/59c47710e83f7797da64ae9fbd2ec7857152b0bc/webapi/src/test/scala/org/knora/webapi/responders/v1/ResourcesResponderV1SpecContextData.scala
- test case: https://github.com/dhlab-basel/Knora/blob/d1cd7064d56193c50aa0b35bf3a07b71b2191290/webapi/src/test/scala/org/knora/webapi/responders/v1/ResourcesResponderV1Spec.scala

**Comment by loicjaouen** [comment]
Note: the data is correctly handled in the triple store, the information is lost in the resource responder

**Comment by benjamingeer** [comment]
I remember that we did it this way to imitate the old SALSAH, in which the GUI doesn’t use the last modification date. But this should be easy to add.

**Comment by gfoo** [comment]
maybe fixed by #952 ?
