### ISSUE TITLE
How should we export files from the old SALSAH?

### ISSUE THREAD

**Issue by benjamingeer** [dasch-swiss/dsp-api#83]
The current export script exports metadata but not files. How can we export a whole project from the old SALSAH, including its files, so it can be imported into Knora, enabling Sipi to serve the files? Would it be feasible for the export script to do this? It would have to associate each `FileValue` with a filename and path suitable for Sipi, and copy the files into the directory structure that Sipi expects.

cc @lrosenth

**Comment by musicEnfanthen** [comment]
see also #509

**Comment by benjamingeer** [comment]
This is the plan: https://github.com/dhlab-basel/Knora/pull/491#discussion_r119094961

**Comment by subotic** [comment]
@lrosenth is extending the PHP Salsah API so it will generate `ttl` and `xml` with all the data, which then can be imported into Knora.
