### ISSUE TITLE
Sipi Responder should tell what to do in Case of restricted View

### ISSUE THREAD

**Issue by tobiasschweizer** [dasch-swiss/dsp-api#86]
If Sipi responder returns a permission code 1, Sipi has to return the requested image in restricted view mode. This can mean two things: either return the image with a watermark or in a reduced size.

Where would that information be stored?

**Comment by subotic** [comment]
The information which the sipi responder sends back to sipi should be clear. It shouldn't be up to sipi to decide what to serve. If the permissions given can mean two things, then they are not deterministic, which is bad in-itself. Just my thoughts :-)

**Comment by tobiasschweizer** [comment]
At the moment, Knora just returns a permission code:

- no access (Sipi denies access to the image file)
- restricted view (Sipi could render a watermark into it or serve a reduced size/resolution of the image)
- viewing rights (Sipi serves the image in the desired quality)

Additionally, Knora should tell Sipi what to do in the case of restricted view. So the information must go somewhere in the triplestore, so Knora can query it.

**Comment by subotic** [comment]
I agree. This needs to be inside Knora somewhere. This will probably be a project setting, since restricted view changes it's meaning depending on the project, hence the non-determinism.

**Comment by subotic** [comment]
This is probably another thing that I need to consider in #54 or #1 or #79 .

**Comment by mrivoal** [comment]
Salsah give a '404 Not found' error when a user tries to open a resource with Restricted View permission.
