### ISSUE TITLE
Define OWL Metaclasses to set Restrictions for Resource Classes

### ISSUE THREAD

**Issue by tobiasschweizer** [dasch-swiss/dsp-api#91]
see https://en.wikipedia.org/wiki/Metaclass_%28Semantic_Web%29

Define restrictions for Knora resources classes such as for resource icon, label ...

Like this we can be sure that certain properties are given for resource classes (to prevent bugs in Scala).

For example, the resource class (not the instance) book needs to have a label or a resource icon.

**Comment by tobiasschweizer** [comment]
How can we make sure that a string is not empty? In `knora-base.ttl`, we have this for a region:

```turtle
rdfs:label """""" ;
```

**Comment by benjamingeer** [comment]
I'll find out whether it's possible to check this with the GraphDB consistency checker.

**Comment by tobiasschweizer** [comment]
We have to fix this in the data, otherwise we can not rely that these props exist when we access them from scala, resulting errors like this when searching for regions:

```no-highlight
No value found for SPARQL query variable 'resourceLabel' in query result row
webapi org.knora.webapi.InconsistentTriplestoreDataException: No value found for SPARQL query variable 'resourceLabel' in query result row
```

Empty results are filtered out and thus this behaves as if it wasn't there at all.
