### ISSUE TITLE
Loading Strings  from SALSAH /lang

### ISSUE THREAD

**Issue by tobiasschweizer** [dasch-swiss/dsp-api#92]
In `00_init_javascript.js`, the label strings are initialized by doing a Get-request.

The plugin `jquery.dateobj.js` tries to access these before they are actually there, resulting in `undefined` label strings.

We should use a promise in `00_init_javascript.js` here to make sure, that the Get request has been completed before continuing.

**Comment by tobiasschweizer** [comment]
`00_init_javascript.js`:

```javascript
var strings = {};
$.get('lang/' + SALSAH.userdata.lang + '.json', function(data) {
	strings = data;
}, 'json');
```

**Comment by seakayone** [comment]
This issue has been inactive for a significant time, so we’re closing it for now. If it’s still relevant, feel free to reopen.
