### ISSUE TITLE
Check consistency of knora-base:ExternalResource

### ISSUE THREAD

**Issue by tobiasschweizer** [dasch-swiss/dsp-api#94]
In `knora-base.ttl`, `ExternalResource` is defined as a non Knora Resource.

``` turtle
###  http://www.knora.org/ontology/knora-base#ExternalResource

:ExternalResource rdf:type owl:Class ;

                  rdfs:subClassOf :Resource ,
                                  [ rdf:type owl:Restriction ;
                                    owl:onProperty :hasExtResValue ;
                                    owl:cardinality "1"^^xsd:nonNegativeInteger
                                  ] ;

                  rdfs:comment "Represents a proxy for an object stored by an external provider"@en .
```

The property `hasProvider` has a `subjectClassConstraint` pointing to `ExternalResource`, but no cardinality is defined for this property on `ExternalResource`.

``` turtle
###  http://www.knora.org/ontology/knora-base#hasProvider

:hasProvider rdf:type owl:ObjectProperty ;

             :objectClassConstraint :ExternalResValue ;

             :subjectClassConstraint :ExternalResource ;

             rdfs:subPropertyOf :hasValue .
```

What is the difference between an `ExternalResource` and a `ExternalResValue`? It seems, that the latter behaves like a proxy for a resource, but why do we need `ExternalResource` then?

**Comment by seakayone** [comment]
This issue has been inactive for a significant time, so we’re closing it for now. If it’s still relevant, feel free to reopen.
